services:
  nginx_prod:
    image: nginx:latest
    container_name: docanno_nginx_prod
    restart: always
    ports:
      - "8861:80"
    volumes:
      - ./nginx/conf.prod.d:/etc/nginx/conf.d
    depends_on:
      - docanno_frontend_prod
      - docanno_backend_prod
    networks:
      - internal

  docanno_frontend_prod:
    container_name: docanno_frontend_prod
    build:
      context: ./client
    ports:
      - "3000"
    environment:
      - NODE_ENV=production
    networks:
      - internal

  docanno_backend_prod:
    build:
      context: ./server
    container_name: docanno_backend_prod
    working_dir: /app
    user: "${LOCAL_UID}:${LOCAL_GID}"
    volumes:
      - ./server:/app
    expose:
      - "5000"
    networks:
      - internal

networks:
  internal:
    driver: bridge
