services:
  nginx_dev:
    image: nginx:1.27-alpine
    container_name: docanno_nginx_dev
    restart: always
    ports:
      - "8861:80"
    volumes:
      - ./nginx/conf.dev.d:/etc/nginx/conf.d
    depends_on:
      - docanno_frontend_dev
      - docanno_backend_dev
    networks:
      - internal

  docanno_frontend_dev:
    build:
      context: ./client
    container_name: docanno_frontend_dev
    # image: docanno_frontend_dev
    working_dir: /app
    volumes:
      - ./client:/app
      - docanno_frontend_node_modules:/app/node_modules
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - HOME=/tmp
      - npm_config_cache=/tmp/.npm
    command: sh -c "[ -d /app/node_modules/next ] || npm install --legacy-peer-deps; npx next dev -p 3000 -H 0.0.0.0"
    networks:
      - internal

  docanno_backend_dev:
    build:
      context: ./server
    container_name: docanno_backend_dev
    # image: docanno_backend_dev
    working_dir: /app
    volumes:
      - ./server:/app
    expose:
      - "5000"
    environment:
      FLASK_ENV: development
      HOME: /tmp
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
    command: python -u app.py
    networks:
      - internal


volumes:
  docanno_backend_venv:
  docanno_frontend_node_modules:

networks:
  internal:
    driver: bridge
